Tidy up messages #001

diff --git a/.github/workflows/runMacOS.yml b/.github/workflows/runMacOS.yml
--- a/.github/workflows/runMacOS.yml
+++ b/.github/workflows/runMacOS.yml
@@ -99,7 +99,7 @@ jobs:
            echo "/opt/local/sbin" >> $GITHUB_PATH
            if [[ ${{ inputs.universal }} == true ]]; then
                echo "::notice:: Adding Universal"
-               sudo bash -c "echo +universal >> /opt/local/etc/macports/variants.conf"
+               sudo bash -c "echo +universal >> /opt/local/etc/macports/variants.conf" && echo "::notice:: universal added" || echo "::warning:: adding universal FAILED"
            fi
 
     - name: Backup MacPorts
